[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "QDesignOptimizer"
dynamic = ["version"]
authors = [
  {name="QDesignOptimizer developers"},
]
description = "Automatic multi-parameter design optimization for superconducting quantum devices"
readme = "README.md"
# This project follows https://scientific-python.org/specs/spec-0000/
requires-python = "==3.10"
dependencies = [
    "sympy>=1.12",
    "python-mumps>=0.0.1,<0.1",
    "packaging>=22.0",  # For version parsing

]
[tool.hatch.build.targets.sdist]
include = [
  "QDesignOptimizer",
  "README.md",
  "LICENSE",
  "pyproject.toml",
  "pytest.ini",
  "AUTHORS.md",
  "requirements.txt"
]
