name: Lint-Test-Mypy

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest"]
        python-version: ["3.10.4"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: 'latest'
          channels: conda-forge
          mamba-version: "*"
          channel-priority: true
          auto-update-conda: false
          auto-activate-base: false
          environment-file: environment.yml
          activate-environment: qdesignenv
      - name: Install project and dependencies
        run: |
          conda activate qdesignenv
          poetry install --with analysis
          pip install --no-deps qiskit-metal==0.1.5
      - name: Analyze the code with pylint
        run: |
          pylint src || pylint-exit $?
      - name: Run tests
        run: |
          pytest tests
      - name: Analyze the code with Mypy
        run: |
          mypy src
