name: Docs
on: [push]

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            label: win-64
            prefix: C:\Miniconda3\envs\qdesignenv
    steps:
      - uses: actions/checkout@v4
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
            miniforge-version: latest
            activate-environment: qdesignenv
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.prefix }}
          key: ${{ matrix.label }}-conda-${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
        id: cache
      - name: Update environment
        run: conda env update -n qdesignenv -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Install project and documentation dependencies
        shell: pwsh
        run: |
          poetry install --with docs
          pip install --no-deps qiskit-metal==0.1.5
      - name: Install Pandoc
        shell: pwsh
        run: |
          choco install pandoc
      - name: Compile documentation
        shell: pwsh
        run: |
          cd docs
          sphinx-build source build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
